'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2032
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class dsPartDesc
    Inherits DataSet
    
    Private tablePartMaster As PartMasterDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("PartMaster")) Is Nothing) Then
                Me.Tables.Add(New PartMasterDataTable(ds.Tables("PartMaster")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property PartMaster As PartMasterDataTable
        Get
            Return Me.tablePartMaster
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As dsPartDesc = CType(MyBase.Clone,dsPartDesc)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("PartMaster")) Is Nothing) Then
            Me.Tables.Add(New PartMasterDataTable(ds.Tables("PartMaster")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tablePartMaster = CType(Me.Tables("PartMaster"),PartMasterDataTable)
        If (Not (Me.tablePartMaster) Is Nothing) Then
            Me.tablePartMaster.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "dsPartDesc"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/dsPartDesc.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tablePartMaster = New PartMasterDataTable
        Me.Tables.Add(Me.tablePartMaster)
    End Sub
    
    Private Function ShouldSerializePartMaster() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub PartMasterRowChangeEventHandler(ByVal sender As Object, ByVal e As PartMasterRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class PartMasterDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnPartNumber As DataColumn
        
        Private columnDescText As DataColumn
        
        Private columnRevision As DataColumn
        
        Friend Sub New()
            MyBase.New("PartMaster")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property PartNumberColumn As DataColumn
            Get
                Return Me.columnPartNumber
            End Get
        End Property
        
        Friend ReadOnly Property DescTextColumn As DataColumn
            Get
                Return Me.columnDescText
            End Get
        End Property
        
        Friend ReadOnly Property RevisionColumn As DataColumn
            Get
                Return Me.columnRevision
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As PartMasterRow
            Get
                Return CType(Me.Rows(index),PartMasterRow)
            End Get
        End Property
        
        Public Event PartMasterRowChanged As PartMasterRowChangeEventHandler
        
        Public Event PartMasterRowChanging As PartMasterRowChangeEventHandler
        
        Public Event PartMasterRowDeleted As PartMasterRowChangeEventHandler
        
        Public Event PartMasterRowDeleting As PartMasterRowChangeEventHandler
        
        Public Overloads Sub AddPartMasterRow(ByVal row As PartMasterRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddPartMasterRow(ByVal PartNumber As String, ByVal DescText As String, ByVal Revision As String) As PartMasterRow
            Dim rowPartMasterRow As PartMasterRow = CType(Me.NewRow,PartMasterRow)
            rowPartMasterRow.ItemArray = New Object() {PartNumber, DescText, Revision}
            Me.Rows.Add(rowPartMasterRow)
            Return rowPartMasterRow
        End Function
        
        Public Function FindByPartNumber(ByVal PartNumber As String) As PartMasterRow
            Return CType(Me.Rows.Find(New Object() {PartNumber}),PartMasterRow)
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As PartMasterDataTable = CType(MyBase.Clone,PartMasterDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New PartMasterDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnPartNumber = Me.Columns("PartNumber")
            Me.columnDescText = Me.Columns("DescText")
            Me.columnRevision = Me.Columns("Revision")
        End Sub
        
        Private Sub InitClass()
            Me.columnPartNumber = New DataColumn("PartNumber", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnPartNumber)
            Me.columnDescText = New DataColumn("DescText", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnDescText)
            Me.columnRevision = New DataColumn("Revision", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnRevision)
            Me.Constraints.Add(New UniqueConstraint("Constraint1", New DataColumn() {Me.columnPartNumber}, true))
            Me.columnPartNumber.AllowDBNull = false
            Me.columnPartNumber.Unique = true
        End Sub
        
        Public Function NewPartMasterRow() As PartMasterRow
            Return CType(Me.NewRow,PartMasterRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New PartMasterRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(PartMasterRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.PartMasterRowChangedEvent) Is Nothing) Then
                RaiseEvent PartMasterRowChanged(Me, New PartMasterRowChangeEvent(CType(e.Row,PartMasterRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.PartMasterRowChangingEvent) Is Nothing) Then
                RaiseEvent PartMasterRowChanging(Me, New PartMasterRowChangeEvent(CType(e.Row,PartMasterRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.PartMasterRowDeletedEvent) Is Nothing) Then
                RaiseEvent PartMasterRowDeleted(Me, New PartMasterRowChangeEvent(CType(e.Row,PartMasterRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.PartMasterRowDeletingEvent) Is Nothing) Then
                RaiseEvent PartMasterRowDeleting(Me, New PartMasterRowChangeEvent(CType(e.Row,PartMasterRow), e.Action))
            End If
        End Sub
        
        Public Sub RemovePartMasterRow(ByVal row As PartMasterRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class PartMasterRow
        Inherits DataRow
        
        Private tablePartMaster As PartMasterDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tablePartMaster = CType(Me.Table,PartMasterDataTable)
        End Sub
        
        Public Property PartNumber As String
            Get
                Return CType(Me(Me.tablePartMaster.PartNumberColumn),String)
            End Get
            Set
                Me(Me.tablePartMaster.PartNumberColumn) = value
            End Set
        End Property
        
        Public Property DescText As String
            Get
                Try 
                    Return CType(Me(Me.tablePartMaster.DescTextColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePartMaster.DescTextColumn) = value
            End Set
        End Property
        
        Public Property Revision As String
            Get
                Try 
                    Return CType(Me(Me.tablePartMaster.RevisionColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePartMaster.RevisionColumn) = value
            End Set
        End Property
        
        Public Function IsDescTextNull() As Boolean
            Return Me.IsNull(Me.tablePartMaster.DescTextColumn)
        End Function
        
        Public Sub SetDescTextNull()
            Me(Me.tablePartMaster.DescTextColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsRevisionNull() As Boolean
            Return Me.IsNull(Me.tablePartMaster.RevisionColumn)
        End Function
        
        Public Sub SetRevisionNull()
            Me(Me.tablePartMaster.RevisionColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class PartMasterRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As PartMasterRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As PartMasterRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As PartMasterRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
