'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2032
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class dsProfile
    Inherits DataSet
    
    Private tableProfileMaster As ProfileMasterDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("ProfileMaster")) Is Nothing) Then
                Me.Tables.Add(New ProfileMasterDataTable(ds.Tables("ProfileMaster")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property ProfileMaster As ProfileMasterDataTable
        Get
            Return Me.tableProfileMaster
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As dsProfile = CType(MyBase.Clone,dsProfile)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("ProfileMaster")) Is Nothing) Then
            Me.Tables.Add(New ProfileMasterDataTable(ds.Tables("ProfileMaster")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableProfileMaster = CType(Me.Tables("ProfileMaster"),ProfileMasterDataTable)
        If (Not (Me.tableProfileMaster) Is Nothing) Then
            Me.tableProfileMaster.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "dsProfile"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/dsProfile.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableProfileMaster = New ProfileMasterDataTable
        Me.Tables.Add(Me.tableProfileMaster)
    End Sub
    
    Private Function ShouldSerializeProfileMaster() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub ProfileMasterRowChangeEventHandler(ByVal sender As Object, ByVal e As ProfileMasterRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class ProfileMasterDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnPartNumber As DataColumn
        
        Private columnProductCode As DataColumn
        
        Private columnOEMPartNumber As DataColumn
        
        Friend Sub New()
            MyBase.New("ProfileMaster")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property PartNumberColumn As DataColumn
            Get
                Return Me.columnPartNumber
            End Get
        End Property
        
        Friend ReadOnly Property ProductCodeColumn As DataColumn
            Get
                Return Me.columnProductCode
            End Get
        End Property
        
        Friend ReadOnly Property OEMPartNumberColumn As DataColumn
            Get
                Return Me.columnOEMPartNumber
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As ProfileMasterRow
            Get
                Return CType(Me.Rows(index),ProfileMasterRow)
            End Get
        End Property
        
        Public Event ProfileMasterRowChanged As ProfileMasterRowChangeEventHandler
        
        Public Event ProfileMasterRowChanging As ProfileMasterRowChangeEventHandler
        
        Public Event ProfileMasterRowDeleted As ProfileMasterRowChangeEventHandler
        
        Public Event ProfileMasterRowDeleting As ProfileMasterRowChangeEventHandler
        
        Public Overloads Sub AddProfileMasterRow(ByVal row As ProfileMasterRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddProfileMasterRow(ByVal PartNumber As String, ByVal ProductCode As String, ByVal OEMPartNumber As String) As ProfileMasterRow
            Dim rowProfileMasterRow As ProfileMasterRow = CType(Me.NewRow,ProfileMasterRow)
            rowProfileMasterRow.ItemArray = New Object() {PartNumber, ProductCode, OEMPartNumber}
            Me.Rows.Add(rowProfileMasterRow)
            Return rowProfileMasterRow
        End Function
        
        Public Function FindByPartNumber(ByVal PartNumber As String) As ProfileMasterRow
            Return CType(Me.Rows.Find(New Object() {PartNumber}),ProfileMasterRow)
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As ProfileMasterDataTable = CType(MyBase.Clone,ProfileMasterDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New ProfileMasterDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnPartNumber = Me.Columns("PartNumber")
            Me.columnProductCode = Me.Columns("ProductCode")
            Me.columnOEMPartNumber = Me.Columns("OEMPartNumber")
        End Sub
        
        Private Sub InitClass()
            Me.columnPartNumber = New DataColumn("PartNumber", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnPartNumber)
            Me.columnProductCode = New DataColumn("ProductCode", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnProductCode)
            Me.columnOEMPartNumber = New DataColumn("OEMPartNumber", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnOEMPartNumber)
            Me.Constraints.Add(New UniqueConstraint("Constraint1", New DataColumn() {Me.columnPartNumber}, true))
            Me.columnPartNumber.AllowDBNull = false
            Me.columnPartNumber.Unique = true
        End Sub
        
        Public Function NewProfileMasterRow() As ProfileMasterRow
            Return CType(Me.NewRow,ProfileMasterRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New ProfileMasterRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(ProfileMasterRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.ProfileMasterRowChangedEvent) Is Nothing) Then
                RaiseEvent ProfileMasterRowChanged(Me, New ProfileMasterRowChangeEvent(CType(e.Row,ProfileMasterRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.ProfileMasterRowChangingEvent) Is Nothing) Then
                RaiseEvent ProfileMasterRowChanging(Me, New ProfileMasterRowChangeEvent(CType(e.Row,ProfileMasterRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.ProfileMasterRowDeletedEvent) Is Nothing) Then
                RaiseEvent ProfileMasterRowDeleted(Me, New ProfileMasterRowChangeEvent(CType(e.Row,ProfileMasterRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.ProfileMasterRowDeletingEvent) Is Nothing) Then
                RaiseEvent ProfileMasterRowDeleting(Me, New ProfileMasterRowChangeEvent(CType(e.Row,ProfileMasterRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveProfileMasterRow(ByVal row As ProfileMasterRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class ProfileMasterRow
        Inherits DataRow
        
        Private tableProfileMaster As ProfileMasterDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableProfileMaster = CType(Me.Table,ProfileMasterDataTable)
        End Sub
        
        Public Property PartNumber As String
            Get
                Return CType(Me(Me.tableProfileMaster.PartNumberColumn),String)
            End Get
            Set
                Me(Me.tableProfileMaster.PartNumberColumn) = value
            End Set
        End Property
        
        Public Property ProductCode As String
            Get
                Try 
                    Return CType(Me(Me.tableProfileMaster.ProductCodeColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableProfileMaster.ProductCodeColumn) = value
            End Set
        End Property
        
        Public Property OEMPartNumber As String
            Get
                Try 
                    Return CType(Me(Me.tableProfileMaster.OEMPartNumberColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableProfileMaster.OEMPartNumberColumn) = value
            End Set
        End Property
        
        Public Function IsProductCodeNull() As Boolean
            Return Me.IsNull(Me.tableProfileMaster.ProductCodeColumn)
        End Function
        
        Public Sub SetProductCodeNull()
            Me(Me.tableProfileMaster.ProductCodeColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsOEMPartNumberNull() As Boolean
            Return Me.IsNull(Me.tableProfileMaster.OEMPartNumberColumn)
        End Function
        
        Public Sub SetOEMPartNumberNull()
            Me(Me.tableProfileMaster.OEMPartNumberColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class ProfileMasterRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As ProfileMasterRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As ProfileMasterRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As ProfileMasterRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
