'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.2032
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class dsWorkOrder
    Inherits DataSet
    
    Private tableWOHeader As WOHeaderDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("WOHeader")) Is Nothing) Then
                Me.Tables.Add(New WOHeaderDataTable(ds.Tables("WOHeader")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property WOHeader As WOHeaderDataTable
        Get
            Return Me.tableWOHeader
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As dsWorkOrder = CType(MyBase.Clone,dsWorkOrder)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("WOHeader")) Is Nothing) Then
            Me.Tables.Add(New WOHeaderDataTable(ds.Tables("WOHeader")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableWOHeader = CType(Me.Tables("WOHeader"),WOHeaderDataTable)
        If (Not (Me.tableWOHeader) Is Nothing) Then
            Me.tableWOHeader.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "dsWorkOrder"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/dsWorkOrder.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableWOHeader = New WOHeaderDataTable
        Me.Tables.Add(Me.tableWOHeader)
    End Sub
    
    Private Function ShouldSerializeWOHeader() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub WOHeaderRowChangeEventHandler(ByVal sender As Object, ByVal e As WOHeaderRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class WOHeaderDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnWONumber As DataColumn
        
        Private columnQuantityRequired As DataColumn
        
        Private columnPartNumber As DataColumn
        
        Friend Sub New()
            MyBase.New("WOHeader")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property WONumberColumn As DataColumn
            Get
                Return Me.columnWONumber
            End Get
        End Property
        
        Friend ReadOnly Property QuantityRequiredColumn As DataColumn
            Get
                Return Me.columnQuantityRequired
            End Get
        End Property
        
        Friend ReadOnly Property PartNumberColumn As DataColumn
            Get
                Return Me.columnPartNumber
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As WOHeaderRow
            Get
                Return CType(Me.Rows(index),WOHeaderRow)
            End Get
        End Property
        
        Public Event WOHeaderRowChanged As WOHeaderRowChangeEventHandler
        
        Public Event WOHeaderRowChanging As WOHeaderRowChangeEventHandler
        
        Public Event WOHeaderRowDeleted As WOHeaderRowChangeEventHandler
        
        Public Event WOHeaderRowDeleting As WOHeaderRowChangeEventHandler
        
        Public Overloads Sub AddWOHeaderRow(ByVal row As WOHeaderRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddWOHeaderRow(ByVal WONumber As String, ByVal QuantityRequired As Double, ByVal PartNumber As String) As WOHeaderRow
            Dim rowWOHeaderRow As WOHeaderRow = CType(Me.NewRow,WOHeaderRow)
            rowWOHeaderRow.ItemArray = New Object() {WONumber, QuantityRequired, PartNumber}
            Me.Rows.Add(rowWOHeaderRow)
            Return rowWOHeaderRow
        End Function
        
        Public Function FindByWONumber(ByVal WONumber As String) As WOHeaderRow
            Return CType(Me.Rows.Find(New Object() {WONumber}),WOHeaderRow)
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As WOHeaderDataTable = CType(MyBase.Clone,WOHeaderDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New WOHeaderDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnWONumber = Me.Columns("WONumber")
            Me.columnQuantityRequired = Me.Columns("QuantityRequired")
            Me.columnPartNumber = Me.Columns("PartNumber")
        End Sub
        
        Private Sub InitClass()
            Me.columnWONumber = New DataColumn("WONumber", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnWONumber)
            Me.columnQuantityRequired = New DataColumn("QuantityRequired", GetType(System.Double), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnQuantityRequired)
            Me.columnPartNumber = New DataColumn("PartNumber", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnPartNumber)
            Me.Constraints.Add(New UniqueConstraint("Constraint1", New DataColumn() {Me.columnWONumber}, true))
            Me.columnWONumber.AllowDBNull = false
            Me.columnWONumber.Unique = true
        End Sub
        
        Public Function NewWOHeaderRow() As WOHeaderRow
            Return CType(Me.NewRow,WOHeaderRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New WOHeaderRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(WOHeaderRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.WOHeaderRowChangedEvent) Is Nothing) Then
                RaiseEvent WOHeaderRowChanged(Me, New WOHeaderRowChangeEvent(CType(e.Row,WOHeaderRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.WOHeaderRowChangingEvent) Is Nothing) Then
                RaiseEvent WOHeaderRowChanging(Me, New WOHeaderRowChangeEvent(CType(e.Row,WOHeaderRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.WOHeaderRowDeletedEvent) Is Nothing) Then
                RaiseEvent WOHeaderRowDeleted(Me, New WOHeaderRowChangeEvent(CType(e.Row,WOHeaderRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.WOHeaderRowDeletingEvent) Is Nothing) Then
                RaiseEvent WOHeaderRowDeleting(Me, New WOHeaderRowChangeEvent(CType(e.Row,WOHeaderRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveWOHeaderRow(ByVal row As WOHeaderRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class WOHeaderRow
        Inherits DataRow
        
        Private tableWOHeader As WOHeaderDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableWOHeader = CType(Me.Table,WOHeaderDataTable)
        End Sub
        
        Public Property WONumber As String
            Get
                Return CType(Me(Me.tableWOHeader.WONumberColumn),String)
            End Get
            Set
                Me(Me.tableWOHeader.WONumberColumn) = value
            End Set
        End Property
        
        Public Property QuantityRequired As Double
            Get
                Try 
                    Return CType(Me(Me.tableWOHeader.QuantityRequiredColumn),Double)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableWOHeader.QuantityRequiredColumn) = value
            End Set
        End Property
        
        Public Property PartNumber As String
            Get
                Try 
                    Return CType(Me(Me.tableWOHeader.PartNumberColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableWOHeader.PartNumberColumn) = value
            End Set
        End Property
        
        Public Function IsQuantityRequiredNull() As Boolean
            Return Me.IsNull(Me.tableWOHeader.QuantityRequiredColumn)
        End Function
        
        Public Sub SetQuantityRequiredNull()
            Me(Me.tableWOHeader.QuantityRequiredColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsPartNumberNull() As Boolean
            Return Me.IsNull(Me.tableWOHeader.PartNumberColumn)
        End Function
        
        Public Sub SetPartNumberNull()
            Me(Me.tableWOHeader.PartNumberColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class WOHeaderRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As WOHeaderRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As WOHeaderRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As WOHeaderRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
